VEHICLE_PARTS_DICT = {
    'Tailgate': 'B',
    'Wagon Unibody': 'M',
    'Rear Bumper': 'B',
    'Front Bumper Support': 'F',
    'Front Bumper': 'F',
    'Hood': 'F',
    'Right Headlight': 'FR',
    'Left Headlight': 'FL',
    'Front Right Fender': 'FR',
    'Front Left Fender': 'FL',
    'Single Exhaust': 'B',
    'Front Right Door': 'MR',
    'Front Left Door': 'ML',
    'Rear Right Door': 'MR',
    'Rear Left Door': 'ML',
    'Wagon Right Taillight': 'MR',
    'Right Mirror': 'FR',
    'Left Mirror': 'FL',
    "Dual Outlet Exhaust": "B",
    "Wagon Left Taillight": "ML",
    "Radiator": 'F',
    "Independent Front Suspension": 'F',
    "Independent Rear Suspension": 'B',
    "Steering": 'FL',
    "Tailgate Glass": 'B',
    "Front Strut Brace": 'F',
    "Front Left Door Glass": "FL",
    "Front Right Door Glass": "FR",
    "Passenger Seat": "FR",
    "Driver Seat": "FL",
    "Front Spindles": 'F',
    "Rear Spindles": 'B',
    "Rear Right Door Glass": "BR",
    "Rear Left Door Glass": "BL",
    "Rear Seats": 'R',
    "Front Sway Bar": 'F'
}

# TODO: find a position of this component
# "Glass"
